FROM node:12.13.0

WORKDIR /usr/src/nodeapp2

RUN npm install -g npm@6.12.0
RUN npm install -g typescript@3.6.4
RUN npm install -g @angular/cli@8.3.14

COPY . /usr/src/nodeapp2

RUN npm install -g react-scripts@3.2.0
RUN npm install --save express@4.17.1
RUN npm install --save @ngx-translate/core@11.0.1
RUN npm install --save @ngx-translate/http-loader@4.0.0
RUN npm install --save ngx-device-detector@1.3.12
RUN npm install --save @angular/material@8.2.3
RUN npm install --save @angular/cdk@8.2.3
RUN npm install --save @angular/animations@8.1.3
RUN npm install --save web-animations-js@2.3.2
RUN npm install --save hammerjs@2.0.8
RUN npm install angular-user-idle@2.2.1
RUN npm install rxjs@6.4.0
RUN npm install @reactivex/rxjs@6.5.3
RUN npm install
RUN npm audit fix
CMD ng add @angular/material




