FROM python:3.7.4

# Set environment variables
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /

RUN pip install --upgrade pip
# Install dependencies.
RUN pip install -r /requirements.txt

# Set work directory.
RUN mkdir /code-app2
WORKDIR /code-app2

# Copy project code-app2.
COPY . /code-app2/

EXPOSE 9900